apiVersion: v1
kind: Service
metadata:
  name: nginx-demos8
  labels:
    app: nginx8
spec:
  type: ClusterIP
  selector:
    app: nginx8
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
