apiVersion: v1
kind: Service
metadata:
  name: nginx-demos6
  labels:
    app: nginx6
spec:
  type: ClusterIP
  selector:
    app: nginx6
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
