apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx10
  template:
    metadata:
      labels:
        app: nginx10
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            memory: "32Mi"
          limits:
            memory: "64Mi"
