apiVersion: v1
kind: Service
metadata:
  name: nginx-demos10
  labels:
    app: nginx10
spec:
  type: ClusterIP
  selector:
    app: nginx10
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
