apiVersion: v1
kind: Service
metadata:
  name: nginx-demos3
  labels:
    app: nginx3
spec:
  type: ClusterIP
  selector:
    app: nginx3
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
