apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx9
  template:
    metadata:
      labels:
        app: nginx9
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            memory: "32Mi"
          limits:
            memory: "64Mi"
