apiVersion: v1
kind: Service
metadata:
  name: nginx-demos9
  labels:
    app: nginx9
spec:
  type: ClusterIP
  selector:
    app: nginx9
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
