apiVersion: v1
kind: Service
metadata:
  name: nginx-demos5
  labels:
    app: nginx5
spec:
  type: ClusterIP
  selector:
    app: nginx5
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
